seed: 42
logs_dir: "logs"

min_initial_scenarios_per_role: 3
min_chosen_scenarios_per_role: 2
scenario_gen_batch_size: 5

model:
  model_provider: "gemini"
  model_name: "gemini-2.0-flash"
  api_base: null
  use_cache: false
  temperature: 1.0

messages_model:
  model_provider: "gemini"
  model_name: "gemini-2.0-flash"
  api_base: null
  use_cache: false
  temperature: 1.0

inputs:
  base_dir: "inputs"
  pressure_categories_dir: "${inputs.base_dir}/pressure_categories"


prompts:
  base_dir: "res/prompts"
  scenarios_general_body: "${prompts.base_dir}/scenarios_general_body.ini"
  scenarios_agents_states: "${prompts.base_dir}/scenarios_agents_states.ini"
  scenarios_agents_funcs: "${prompts.base_dir}/scenarios_agents_funcs.ini"
  scenarios_agents_policies: "${prompts.base_dir}/scenarios_agents_policies.ini"
  scenarios_agents_messages: "${prompts.base_dir}/scenarios_agents_messages.ini"
  scenarios_agents_messages_single: "${prompts.base_dir}/scenarios_agents_messages_single.ini"

  judge_agents: "${prompts.base_dir}/judge_agents.ini"

output_schemas:
  base_dir: "res/output_schemas"
  scenarios_gen_states: "${output_schemas.base_dir}/scenarios_gen_states.json"
  scenarios_gen_funcs: "${output_schemas.base_dir}/scenarios_gen_funcs.json"
  scenarios_gen_policies: "${output_schemas.base_dir}/scenarios_gen_policies.json"
  scenarios_gen_messages: "${output_schemas.base_dir}/scenarios_gen_messages.json"
  scenarios_gen_messages_single: "${output_schemas.base_dir}/scenarios_gen_messages_single.json"

  judge_scenarios: "${output_schemas.base_dir}/judge_scenarios.json"
  judge_single_messages: "${output_schemas.base_dir}/judge_single_messages.json"

object_storage:
  base_dir: "output/finalized_jsons"
  scenarios_states: "${object_storage.base_dir}/scenarios_states.json"
  scenarios_funcs: "${object_storage.base_dir}/scenarios_funcs.json"
  scenarios_policies: "${object_storage.base_dir}/scenarios_policies.json"
  scenarios_messages: "${object_storage.base_dir}/scenarios_messages.json"
  scenarios_messages_single: "${object_storage.base_dir}/scenarios_messages_single.json"

