#defaults:
#  _self
#  - sys_prompts: default

seed: 42
logs_dir: "logs"

n_initial_roles: 20
n_min_initial_roles: 10
n_roles: 10 # Number of roles selected out of the initial batch
min_initial_scenarios_per_role: 5
min_chosen_scenarios_per_role: 2
scenario_gen_batch_size: 20

#n_retries: 5

model:
  #  model_provider: "openai"
  model_provider: "gemini"
  #  model_name: "llama3.1-8b-instruct"
  model_name: "gemini-1.5-flash"
  #  api_base: http://localhost:8000/v1
  api_base: null
  use_cache: false
  temperature: 1.0

prompts:
  base_dir: "res/prompts"
  roles_agents: "${prompts.base_dir}/roles_agents.ini"
  #  scenarios_agents: "${prompts.base_dir}/scenarios_agents.ini"
  scenarios_agents_states: "${prompts.base_dir}/scenarios_agents_states.ini"
  scenarios_agents_funcs: "${prompts.base_dir}/scenarios_agents_funcs.ini"
  scenarios_agents_policies: "${prompts.base_dir}/scenarios_agents_policies.ini"
  scenarios_agents_messages: "${prompts.base_dir}/scenarios_agents_messages.ini"

  judge_agents: "${prompts.base_dir}/judge_agents.ini"

output_schemas:
  base_dir: "res/output_schemas"
  roles_generation: "${output_schemas.base_dir}/roles_generation.json"
  #  scenarios_generation: "${output_schemas.base_dir}/scenarios_generation3.json"
  scenarios_gen_states: "${output_schemas.base_dir}/scenarios_gen_states.json"
  scenarios_gen_funcs: "${output_schemas.base_dir}/scenarios_gen_funcs.json"
  scenarios_gen_policies: "${output_schemas.base_dir}/scenarios_gen_policies.json"
  scenarios_gen_messages: "${output_schemas.base_dir}/scenarios_gen_messages.json"

  judge_roles: "${output_schemas.base_dir}/judge_roles.json"
  judge_scenarios: "${output_schemas.base_dir}/judge_scenarios.json"

object_storage:
  base_dir: "output/finalized_jsons"
  roles: "${object_storage.base_dir}/roles.json"
  #  scenarios: "${object_storage.base_dir}/scenarios3.json"
  scenarios_states: "${object_storage.base_dir}/scenarios_states.json"
  scenarios_funcs: "${object_storage.base_dir}/scenarios_funcs.json"
  scenarios_policies: "${object_storage.base_dir}/scenarios_policies.json"
  scenarios_messages: "${object_storage.base_dir}/scenarios_messages.json"

